name: Create/Merge Documentation for GH Pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies and run docs generator
      run: |
        cd $GITHUB_WORKSPACE
        npm install
        npm run docs
    - name: Push to gh-pages branch
      uses: everlytic/branch-merge@1.1.0
      with:
        target_branch: gh-pages
