name: Create/Merge Documentation for GH Pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies and run docs generator
      run: |
        cd $GITHUB_WORKSPACE
        git fetch origin gh-pages:gh-pages
        git clone .git --branch gh-pages docs-gh-pages
        npm install
        npm run docs
        mv docs-dist/* docs-gh-pages/
        cd docs-gh-pages 
        git add --all 
        git commit -m "Publishing to gh-pages" 
        git push origin gh-pages
        cd ../ 
        git push origin gh-pages
